import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

import Homebanner from "@/components/HomeBanner";
import Quality from "@/components/Quality";
import AboutCompany from "@/components/AboutCompany";
import WhyChoose from "@/components/WhyChoose";
import Blogs from "@/components/Blogs";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sarvesh Sanitation Engineers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <div
        className="container-fluid banner-container"
        style={{
          backgroundImage: `url("images/banner/05.jpg")`,
          height: "125vh",
          // backgroundBlendMode: "multiply",
          // backgroundColor: "#0000004a",
        }}
      >
        <Navbar />
        <Homebanner />
      </div>
      <Quality />
      <AboutCompany />
      <WhyChoose />
      <Blogs />
      <Footer />
    </>
  );
}
